# Generated by Django 6.0.7 on 2026-07-26 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('CHEF_SECTION', 'Chef de Section'), ('CHEF_BRIGADE', 'Chef de Brigade'), ('GL', 'Garde Ligne'), ('CN', 'Cantonnier')], max_length=20)),
                ('poste', models.CharField(blank=True, max_length=10, null=True)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('ACTIF', 'Actif'), ('REJETE', 'Rejeté'), ('SUSPENDU', 'Suspendu'), ('ARCHIVE', 'Archivé')], default='EN_ATTENTE', max_length=20)),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'utilisateur',
            },
        ),
    ]
