# Generated by Django 6.0.7 on 2026-07-26 10:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personnel', '0002_remove_brigade_chef_brigade'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Materiel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('categorie', models.CharField(max_length=50)),
                ('seuil_alerte', models.IntegerField(default=5)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'materiel',
            },
        ),
        migrations.CreateModel(
            name='MouvementMateriel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, unique=True)),
                ('type', models.CharField(choices=[('APPROVISIONNEMENT', 'Approvisionnement'), ('EMPRUNT', 'Emprunt'), ('RETOUR', 'Retour'), ('TRANSFERT', 'Transfert'), ('REPARATION', 'Réparation'), ('REBUT', 'Rebus'), ('INVENTAIRE', 'Inventaire')], max_length=20)),
                ('quantite', models.PositiveIntegerField()),
                ('date_mouvement', models.DateField(auto_now_add=True)),
                ('date_retour_prevue', models.DateField(blank=True, null=True)),
                ('date_retour_effective', models.DateField(blank=True, null=True)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('EN_COURS', 'En cours'), ('RETOURNE', 'Retourné'), ('EN_RETARD', 'En retard'), ('PERDU', 'Perdu'), ('ANNULE', 'Annulé')], default='EN_COURS', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent_concerner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouvements_agent', to=settings.AUTH_USER_MODEL)),
                ('brigade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouvements_source', to='personnel.brigade')),
                ('brigade_destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouvements_dest', to='personnel.brigade')),
                ('createur', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='mouvements_cree', to=settings.AUTH_USER_MODEL)),
                ('materiel', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='materiaux.materiel')),
            ],
            options={
                'db_table': 'mouvement_materiel',
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etat', models.CharField(choices=[('NEUF', 'Neuf'), ('BON', 'Bon'), ('MOYEN', 'Moyen'), ('MAUVAIS', 'Mauvais'), ('HORS_SERVICE', 'Hors service')], max_length=20)),
                ('quantite', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('materiel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materiaux.materiel')),
            ],
            options={
                'db_table': 'stock',
                'unique_together': {('materiel', 'etat')},
            },
        ),
    ]
