# Generated by Django 6.0.7 on 2026-08-11 11:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiaux', '0001_initial'),
        ('personnel', '0003_brigade_chef_brigade'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stock',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='mouvementmateriel',
            name='etat',
            field=models.CharField(blank=True, choices=[('NEUF', 'Neuf'), ('BON', 'Bon'), ('MOYEN', 'Moyen'), ('MAUVAIS', 'Mauvais'), ('HORS_SERVICE', 'Hors service')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='brigade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stocks', to='personnel.brigade'),
        ),
        migrations.AlterField(
            model_name='mouvementmateriel',
            name='date_mouvement',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterUniqueTogether(
            name='stock',
            unique_together={('materiel', 'etat', 'brigade')},
        ),
    ]
