# Generated by Django 6.0.7 on 2026-07-26 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brigade',
            name='chef_brigade',
        ),
    ]
