# Generated by Django 6.0.7 on 2026-07-26 10:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0002_remove_brigade_chef_brigade'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='brigade',
            name='chef_brigade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brigade_chef', to=settings.AUTH_USER_MODEL),
        ),
    ]
